version: 0.2

phases:
  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run lint
      - env CI=true npm test
      - npm run build

  post_build:
    commands:
      - aws s3 sync --delete build/ s3://tntlc-development/production
